version: '3.8'

services:
  backend:
    container_name: nextstep-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
