spring:
  datasource:
    url: jdbc:mysql://34.64.182.217:3306/nextstep?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: nextstep98
    password: Rlaxogns98*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 34.47.124.61
      port: 6379
      password: nextstep98
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
          max-wait: 10000ms

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5fba457f416463d2a865286e249f2cd0
            redirect-uri: "https://api.portfolio-nextstep.info/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

jwt:
  secret: pF4ORt/xd3Ym0UHiJwijgtnYHyNd5B7xQKzSxsWnp5M=
  expiration: 86400000
  refresh_expiration: 604800000

frontend:
  oauth2-redirect-url: https://portfolio-nextstep.info/oauth2/redirect

gcp:
  project-id: next-step-460309
  bucket: next-step-assets
  upload-path: uploads/
  credentials:
    path: /app/keys/gcp-key.json

custom:
  kakao:
    admin-key: 95e93a3588a0d8a60b1c0f6e54a920c9