name: Deploy Spring Boot Backend to GCP VM

on:
    push:
        branches:
            - main # main 브랜치에 push될 때 워크플로우 실행

env:
    PROJECT_ID: next-step # ⭐ GCP 프로젝트 ID. 이미지에서 확인된 프로젝트 이름입니다.
    GCR_HOSTNAME: gcr.io
    IMAGE_NAME: spring-boot-backend # ⭐ Docker 이미지 이름 (예: my-api-server)
    VM_INSTANCE_NAME: next-step-backend # ⭐ 배포할 VM 인스턴스 이름
    VM_ZONE: asia-northeast3-a # ⭐ VM이 위치한 정확한 Zone (예: asia-northeast3-a) - 이미지에는 'asia-northeast3'만 있지만, Zone은 'asia-northeast3-a', 'b', 'c' 중 하나여야 합니다. VM 인스턴스 목록에서 next-step-backend 옆의 실제 Zone을 확인하여 정확하게 기입해주세요.
    VM_USER: nextstep9898 # ⭐ VM에 접속할 사용자 이름

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest # 워크플로우를 실행할 가상 환경

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"
                  cache: "gradle" # 또는 'maven'

            - name: Build with Gradle # Gradle 사용 시
              run: |
                  chmod +x gradlew # gradlew 실행 권한 부여
                  ./gradlew clean bootJar # bootJar 태스크로 실행 가능한 JAR 빌드

            # - name: Build with Maven # Maven 사용 시 (Gradle 대신 사용)
            #   run: mvn clean package -DskipTests # 테스트 건너뛰기

            - name: Authenticate to GCP
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                  project_id: ${{ env.PROJECT_ID }}

            - name: Configure Docker to use gcloud as a credential helper
              run: gcloud auth configure-docker ${GCR_HOSTNAME}

            - name: Build & Push Docker image
              run: |
                  docker build -t ${GCR_HOSTNAME}/${PROJECT_ID}/${IMAGE_NAME}:latest .
                  docker push ${GCR_HOSTNAME}/${PROJECT_ID}/${IMAGE_NAME}:latest

            # --- SSH_AND_SCP 액션을 제거하고 gcloud compute ssh 명령어를 직접 사용합니다. ---
            # 이 방법을 사용하면 VM에 SSH 키를 수동으로 등록할 필요 없이,
            # 서비스 계정이 VM에 대한 권한만 있으면 gcloud가 알아서 SSH 접속을 관리합니다.
            - name: Deploy to GCP VM using gcloud SSH
              run: |
                  # VM_ZONE은 반드시 인스턴스가 위치한 정확한 Zone (예: asia-northeast3-a)을 지정해야 합니다.
                  # VM 인스턴스가 'default' 네트워크에 있고, 서비스 계정이 Compute Admin 권한을 가지고 있다면
                  # SSH 접속 및 docker 명령 실행이 가능합니다.
                  gcloud compute ssh ${VM_USER}@${VM_INSTANCE_NAME} \
                    --project=${PROJECT_ID} \
                    --zone=${VM_ZONE} \
                    --command="\
                      sudo docker stop ${IMAGE_NAME} || true && \
                      sudo docker rm ${IMAGE_NAME} || true && \
                      sudo docker pull ${GCR_HOSTNAME}/${PROJECT_ID}/${IMAGE_NAME}:latest && \
                      sudo docker run -d --name ${IMAGE_NAME} -p 8080:8080 ${GCR_HOSTNAME}/${PROJECT_ID}/${IMAGE_NAME}:latest \
                    "
              # gcloud compute ssh를 사용하려면 VM 인스턴스가 `Compute 인스턴스 Admin` 역할이 부여된 서비스 계정으로 실행되거나,
              # 해당 서비스 계정이 SSH 접속 권한이 있어야 합니다.
